### ISSUE TITLE
Post construction method

### ISSUE THREAD

**Issue by aruthane** [mbierlee/poodinis#14]
Is there any plan to introduce some way of initialising an instance after it has been fully resolved before it is returned to the user? Like the PostConstruct annotation or InitializingBean in Spring

**Comment by aruthane** [comment]
Sorry, I see this question was raised and closed recently. I'm closing this.

**Comment by mbierlee** [comment]
At the time there are no plans to implement constructs such as these. I believe the same can be achieved using factory methods within application contexts. If this solution does not solve your problem, do let me know.

**Comment by mbierlee** [comment]
Will be delivered in the next version of Poodinis
