### ISSUE TITLE
Value injection does not work with structs

### ISSUE THREAD

**Issue by ghost91-** [mbierlee/poodinis#20]
The following code does not compile:

```D
import poodinis;

struct MyStruct
{

}

class MyClass
{
    @Value("")
    MyStruct myStruct;
}

void main()
{
    auto dependencies = new shared DependencyContainer();
    dependencies.register!(ValueInjector!MyStruct, MyStructInjector);
    dependencies.register!(MyClass);
}

class MyStructInjector : ValueInjector!MyStruct
{
    MyStruct get(string key)
    {
        return MyStruct();
    }
}
```
Here are the error messages:
```
../../.dub/packages/poodinis-8.0.0/poodinis/source/poodinis/container.d-mixin-397(397,24): Error: undefined identifier app.MyStruct
../../.dub/packages/poodinis-8.0.0/poodinis/source/poodinis/container.d(321,24): Error: template instance poodinis.container.DependencyContainer.callPostConstructors!(ValueInjector!(MyStruct)) error instantiating
../../.dub/packages/poodinis-8.0.0/poodinis/source/poodinis/container.d(265,54):        instantiated from here: resolve!(ValueInjector!(MyStruct), ValueInjector!(MyStruct))
../../.dub/packages/poodinis-8.0.0/poodinis/source/poodinis/autowire.d(214,28):        instantiated from here: resolve!(ValueInjector!(MyStruct))
../../.dub/packages/poodinis-8.0.0/poodinis/source/poodinis/autowire.d(138,49):        instantiated from here: injectValue!("myStruct", 0LU, "", false, MyClass)
../../.dub/packages/poodinis-8.0.0/poodinis/source/poodinis/autowire.d(118,3):        ... (3 instantiations, -v to show) ...
../../.dub/packages/poodinis-8.0.0/poodinis/source/poodinis/container.d(146,47):        instantiated from here: register!(MyClass, MyClass)
source/app.d(18,17):        instantiated from here: register!(MyClass)
dmd failed with exit code 1.
```

**Comment by ghost91-** [comment]
After some research, I found out, that this is not a bug limited to ValueInjector. Template classes in general have this problem. For example, the following program also does not compile:

app.d:
```D
module app;

import poodinis;
import test;

void main()
{
    auto dependencies = new shared DependencyContainer();
    dependencies.register!(TestClass!TestStruct);
    dependencies.register!(AnotherTestClass);
}

class AnotherTestClass
{
    @Autowire TestClass!TestStruct testClass;
}

struct TestStruct
{

}
```

test.d:
```D
module test;

class TestClass(T)
{
    
}
```
The reason is, that in `poodinis.container.DependencyContainer.callPostConstructors` and `poodinis.autowire.AutowiredRegistration.getPreDestructor` only the module of the type that is currently being injected are imported. We also need to import the modules of the template arguments of the type that is currently being injected. Something like the following:
```D
string moduleMixins(Type)()
{
	string ret = `import ` ~ moduleName!Type ~ `;`;
	static if (__traits(compiles, TemplateArgsOf!Type))
	{
		foreach (TemplateArg; TemplateArgsOf!Type)
		{
			static if (!isBasicType!TemplateArg)
				ret ~= `import ` ~ moduleName!TemplateArg ~ `;`;
		}
	}
	return ret;
}
```
and in `poodinis.container.DependencyContainer.callPostConstructors` then
```D
mixin(moduleMixins!Type());
```
instead of
```D
mixin(`import ` ~ moduleName!Type ~ `;`);
```
The same also needs to happen in `poodinis.autowire.AutowiredRegistration.getPreDestructor`. Maybe somewhere else, too, I don't know about that.

**Comment by ghost91-** [comment]
I fear, to fix this properly, we need to do this recursively. The template arguments might be instanciated templates themselves...

**Comment by mbierlee** [comment]
Thank you for reporting this issue. Unfortunately I was so busy fixing this error I didn't see that you replied meanwhile. In the end it seems we came to the same conclusion and same fix. I've just fixed this in the develop branch myself.

Thank you regardless for taking the time to look into it.

Indeed we should do this recursively, I will add this.

**Comment by mbierlee** [comment]
What is still a mystery to me is that the currently existing unit test, which also injected a struct, did succeed.

**Comment by mbierlee** [comment]
Will be fixed in 8.0.1 which I will release shortly

**Comment by ghost91-** [comment]
As I mentioned earlier (in my very long reply), all of this also need to be done in `poodinis.autowire.AutowiredRegistration.getPreDestructor`. Thanks for working on this so quickly!

**Comment by mbierlee** [comment]
I've applied recursively importing types everywhere now

**Comment by ghost91-** [comment]
Thank you, looks good!
