### ISSUE TITLE
is there a way to specify constructor args when registering a class?

### ISSUE THREAD

**Issue by SingingBush** [mbierlee/poodinis#3]
I'm working on a webapp that uses poodinis and [hibernated](https://github.com/buggins/hibernated) and would like to register hibernated's SessionFactory:

```
auto container = DependencyContainer.getInstance();
container.register!(SessionFactory, SessionFactoryImpl);
```

however, the SessionFactoryImpl constructor takes 3 args, is it possible to pass them in somehow? I had tried the following but poodinis doesn't like it:

```
SessionFactory sf = new SessionFactoryImpl(mySchema, mysqlDialect, myDatasource);
auto container = DependencyContainer.getInstance();
container.register!(SessionFactory, sf);
```

if this isn't possible now, can it be done as a new feature. Please provide an example of how to integrate with hibernated.

**Comment by mbierlee** [comment]
Your second example hits close to how you can solve this:
```
SessionFactory sf = new SessionFactoryImpl(mySchema, mysqlDialect, myDatasource);
auto container = DependencyContainer.getInstance();
container.register!(SessionFactory).existingInstance(sf);
```
See TUTORIAL.md for more details.

Constructor injection is on my list of features I want to look at in the future as well as simplified integration with libraries which weren't made with dependency injection in mind.

**Comment by SingingBush** [comment]
thanks, I ended up spotting that in one of the unit tests and tried it out and found that I couldn't use it with my version of dmd. So I've now updated to dmd v2.069.2 but that breaks [hibernated](https://github.com/buggins/hibernated), so I'm now waiting to see [if they release a new update](https://github.com/buggins/hibernated/issues/25).

My day job is mostly Java with Spring, so I'd really like to be able to use more of the convenient features I'm used to having. 

As well as constructor injection I'd really like to have the ability to essentially do an annotated app context. So _Configuration_, _Value_, and _Bean_ or something similar with the _Service_ and _Component_ annotations.

Jpa style orm is my main need though. Do you have any plans to do something like: _poodinis-orm_?

**Comment by mbierlee** [comment]
Annotated app configuration and eventually auto-scanning are on my list of things I will look at in the future.

I have no plans for integration with (jpa-like) ORM frameworks as of yet since my primary use only involves integration within my own frameworks. Whenever I have to integrate with an external library I write a service around it.
