### ISSUE TITLE
Should interfaces work as components?

### ISSUE THREAD

**Issue by andre2007** [mbierlee/poodinis#30]
This coding fails:
`> dub sample.d`

``` d
/+ dub.sdl:
    name "sample"
    dependency "poodinis" version="8.0.3"
+/

import std;
import poodinis;

interface IfFileSystem
{
    string readTextFile(string filePath);
}

class FileSystem : IfFileSystem
{
    string readTextFile(string filePath) {return readText(filePath);}
}

class DefaultApplicationContext : ApplicationContext
{
    @Component
    public IfFileSystem fileSystem()
    {
        return new FileSystem();
    }
}

void main() 
{
    auto dc = new shared DependencyContainer();
    dc.registerContext!DefaultApplicationContext;
    
    auto fs1 = dc.resolve!IfFileSystem;
    auto fs2= dc.resolve!FileSystem; 
}
```

Error
> Error: cannot implicitly convert expression typeid(IfFileSystem) of type object.TypeInfo_Interface to object.TypeInfo_Class

If I change the ApplicationContext class to:

``` d
class DefaultApplicationContext : ApplicationContext
{
    @Component
    public FileSystem fileSystem()
    {
        return new FileSystem();
    }
}
```

This will work `auto fs2= dc.resolve!FileSystem;`.
For `auto fs1 = dc.resolve!IfFileSystem;` an exception is thrown.

It this the expected behavior here?

**Comment by mbierlee** [comment]
At the moment this is expected behavior. Components registered with factory methods should be concrete types. I will see if I can support interfaces as well or otherwise gracefully handle the situation.

**Comment by mbierlee** [comment]
It only occurred to me just now that this is already supported:

```
class DefaultApplicationContext : ApplicationContext {
	@Component
	@RegisterByType!IfFileSystem 
	public FileSystem  filesystem() {
		return new SomeClass();
	}
}
```

You should be able to resolve it by interface type now
