### ISSUE TITLE
Add something for automatically registering the current type

### ISSUE THREAD

**Issue by dhasenan** [mbierlee/poodinis#5]
Low-priority enhancement.

It's mildly annoying but slightly safer to require all types the container supports to be registered somehow. At the moment, the API requires you to call `DependencyContainer.getInstance.register!type` for each type.

It would be nicer to have an `@AutoRegister` attribute. When the container attempts to build a type (either from a direct call from user code to `resolve` or when processing an `@Autowire` attribute), if the type has not explicitly been registered, if it has an `@AutoRegister` attribute, the type is registered automatically.

An alternative possibility is providing a mixin to register the enclosing type. I have employed this in my code. However, this doesn't work quite so well when you are attempting to resolve types inside a module constructor or a type's static constructor -- specifically, if the types are in the current module, the success or failure of the `resolve` calls depends on the order of declaration. This would be a minor thing, but vibe.d recommends putting your application startup code in a shared module constructor.

**Comment by mbierlee** [comment]
Interesting. I would actually prefer an auto component scan like in Spring but a register-on-resolve seems like a workable intermediate solution. I will look at it. The annotation-driven solution is more preferable because letting the container handle registration will get rid of order-dependance.

**Comment by mbierlee** [comment]
Actually it makes more sense to control whether you want to register a type when resolving instead of annotation-driven, so I made it possible to register a type when resolving it. You can add it as persistent container options to automatically do this for all resolves.
