### ISSUE TITLE
no longer builds with LDC

### ISSUE THREAD

**Issue by SingingBush** [mbierlee/poodinis#6]
since [this commit](https://github.com/mbierlee/poodinis/commit/3e11ff1e92ce0ee71355ba8e93be01b37edd05f7#diff-f4c509f30d08f402567822dd95de5db3) I can no longer build projects with [ldc](https://github.com/ldc-developers/ldc) due to:

```
../../../.dub/packages/poodinis-6.0.0/source/poodinis/autowire.d(124): Error: template instance hasUDA!(__traits(getMember, instance, member), AssignNewInstance) template 'hasUDA' is not defined
```

Although this is probably a [ldc](https://github.com/ldc-developers/ldc) problem it may be worth changinf the travis build to use multiple compilers so that these kind of problem can be detected prior to doing a release. Put the following into `.travis.yml`:

```
d:
  - dmd
  - dmd-2.069.2
  - dmd-2.068.2
  - ldc
  - gdc
```

**Comment by mbierlee** [comment]
You need a compiler which is compatible with at least D 2.068.0, which the latest stable LDC is not unfortunately. You could try the latest LDC 0.17.0 beta 2 if this is possible for you.

I will add other compilers and the minimal required DMD compiler to the list of tested compilers
